### ISSUE TITLE
Caching props bug

### ISSUE THREAD

**Issue by atav32** [swipesapp/react-swiss#28]
Seeing a bug with components that depend on props logic. My guess is a corner-case with how prop values are cached and used during hydration?

Right after resetting the local server, the style of components (that use props with Swiss) will sometimes change. This happens on first reload. Subsequent page reloads doesn't fix the issue (i.e. change the styles). Only resetting the server.

I haven't found a deterministic reproduction of the bug yet, but it seems like it's happening when a component is shared between different pages, but has different prop values on those different pages. The first page load will cache the prop value. When the other page loads, it uses the styles with the cached prop values, instead of the ones used for the page.

Let me know if you have more questions. I know it's kind of confusing to explain with words, but I haven't been able to repro on command.

**Comment by kasperpihl** [comment]
If you know which component it is, we can turn on _debug for it and we can inspect what’s going on with the cache. There is a known bug/expected behavior that caches a component using an object as a value the same way. The cache treats objects as “[Object object], which is a little weird, but I wanted to avoid stringifying everything I get in from it.

**Comment by atav32** [comment]
Here's a working example with debug:

On the /real-estate page, http://staging.bytegain.com/real-estate, the contact form at the very bottom of the page has white text and the CSS classes `Contact_ContactForm sw0`. This is the correct style.

<img width="738" alt="screen shot 2018-12-27 at 12 51 54 pm" src="https://user-images.githubusercontent.com/622185/50489552-4a8e4580-09d6-11e9-8276-6e2cd8f0ad73.png">

However, on the /request-demo page, http://staging.bytegain.com/request-demo, the contact form *should have* black text, but instead has white, because it's CSS classes are also `Contact_ContactForm sw0`. Debug says it reused the cache. Since the cache appears to be global, it using the style rules with white text.

<img width="752" alt="screen shot 2018-12-27 at 12 52 17 pm" src="https://user-images.githubusercontent.com/622185/50489571-6abe0480-09d6-11e9-865c-ed162de0a50a.png">

---

Contact.jsx component: https://github.com/ByteGain/engage-website/blob/newswiss/src/client/react/components/form/Contact.jsx#L118

Contact form swiss rules: https://github.com/ByteGain/engage-website/blob/newswiss/src/client/react/components/form/Contact.swiss.js#L10

**Comment by atav32** [comment]
Also, on the /retargeting page, http://staging.bytegain.com/retargeting, there are two Contact components. 

The top one should have black text
<img width="1163" alt="screen shot 2018-12-27 at 12 58 04 pm" src="https://user-images.githubusercontent.com/622185/50489711-19624500-09d7-11e9-83e4-93557537f01c.png">

And the bottom one should have white text
<img width="1166" alt="screen shot 2018-12-27 at 12 58 10 pm" src="https://user-images.githubusercontent.com/622185/50489716-1e26f900-09d7-11e9-861f-fbe859c0f2af.png">


But they both have white text. And debug shows that only one Swiss style was loaded from cache, `Contact_Wrapper sw0`.

**Comment by atav32** [comment]
I remember you mentioned there's a better way to thematically style a component, with some sort of wrapper. What was the syntax for that again? Maybe that'll fix the bug?

**Comment by kasperpihl** [comment]
I think I solved it now.
It was due to both SwissServerSide and SwissProvider both creating a SwissController, and therefore hydrateted twice.
So I merged those two in one.
Let me know if this doesn't work

**Comment by atav32** [comment]
Yup, looks like it's working! You da man 👍

**Comment by kasperpihl** [comment]
Awesome! Happy to hear that :-)

**Comment by atav32** [comment]
Haha actually could you open this back up — the bug is back again with `v0.4.9` 😅 

I deployed to staging.bytegain.com if you want to take a look.

For example, on the /retargeting page (http://staging.bytegain.com/retargeting), 

1) the top form should have black text
2) the main content section with the isometric images should alternate left and right (instead of all the images being on the left)

**Comment by kasperpihl** [comment]
I'm trying to reproduce this locally.
Did you go to a specific page first or something?
I've tried running it in both dev and production settings, just can't get it to happen :S

**Comment by atav32** [comment]
Yeah, on local, restart the server. Before going to any other page, first go to localhost:1234/real-estate. Then open any of the Resource pages in the footer in a new tab.

**Comment by kasperpihl** [comment]
Nice, thanks! I reproduced and tracked down the bug. It is fixed in 0.4.10.

**Comment by atav32** [comment]
Amazing! Thanks!
